name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: nix
    steps:
      - name: Checkout
        uses: http://10.30.0.24:3000/kris/checkout@v4
        with:
          submodules: recursive
      - name: zig build
        run: nix develop --refresh "git+http://10.30.0.24:3000/kris/ci-workflows#0-16-0" --command zci build
      - name: zig build test
        run: nix develop --refresh "git+http://10.30.0.24:3000/kris/ci-workflows#0-16-0" --command zci build test
